# -*- coding: utf-8 -*-
"""member4_visualizations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZBJeIPW4wDzDuyrNpoqU9Z1XqA_77xJa

# Member 4 — Visualizations
SMS Spam Detection | SAIA 2163 Final Project
"""

from google.colab import drive
drive.mount('/content/drive')

# ── Imports ──────────────────────────────────────────────
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from wordcloud import WordCloud
from collections import Counter
import os

os.makedirs('visuals', exist_ok=True)

# ── Load files ────────────────────────────────────────────
df      = pd.read_csv('/content/drive/MyDrive/NLP Project/cleaned_data.csv')
metrics = pd.read_csv('/content/drive/MyDrive/NLP Project/model_comparison_metrics.csv')
cm_data = np.load('/content/drive/MyDrive/NLP Project/confusion_matrices.npz', allow_pickle=True)

cm_nb   = cm_data['nb']
cm_lr   = cm_data['lr']
cm_w2v  = cm_data['lr_w2v']
CLASS_NAMES = ['Ham', 'Spam']

# Word count (raw text so lengths are realistic)
df['word_count'] = df['text'].apply(lambda x: len(str(x).split()))

print('Files loaded.')
print('Dataset shape:', df.shape)
print('Classes:', df['label'].unique())
print('Models in metrics table:', metrics['Model'].tolist())

"""## Chart 1 — Word Cloud (per class)"""

spam_text = ' '.join(df[df['label'] == 'spam']['text_clean'].dropna())
ham_text  = ' '.join(df[df['label'] == 'ham']['text_clean'].dropna())

wc_spam = WordCloud(
    width=800, height=400,
    background_color='white',
    colormap='Reds',
    max_words=100
).generate(spam_text)

wc_ham = WordCloud(
    width=800, height=400,
    background_color='white',
    colormap='Blues',
    max_words=100
).generate(ham_text)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Chart 1 — Word Cloud by Class', fontsize=15, fontweight='bold')

axes[0].imshow(wc_spam, interpolation='bilinear')
axes[0].axis('off')
axes[0].set_title('SPAM Messages', fontsize=13, color='#c0392b', fontweight='bold')

axes[1].imshow(wc_ham, interpolation='bilinear')
axes[1].axis('off')
axes[1].set_title('HAM Messages', fontsize=13, color='#2980b9', fontweight='bold')

plt.tight_layout()
plt.savefig('visuals/chart1_wordcloud.png', dpi=300, bbox_inches='tight')
plt.show()
print('Saved: visuals/chart1_wordcloud.png')

"""## Chart 2 — Class Distribution (Bar + Pie)"""

class_counts = df['label'].value_counts()
class_pct    = df['label'].value_counts(normalize=True) * 100
COLORS = ['#2196F3', '#F44336']   # blue = ham, red = spam

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle('Chart 2 — Class Distribution', fontsize=15, fontweight='bold')

# Bar chart
bars = axes[0].bar(class_counts.index, class_counts.values,
                   color=COLORS, edgecolor='white', linewidth=1.5, width=0.5)
for bar, (label, count) in zip(bars, class_counts.items()):
    axes[0].text(bar.get_x() + bar.get_width()/2,
                 bar.get_height() + 30,
                 f'{count}\n({class_pct[label]:.1f}%)',
                 ha='center', fontsize=11, fontweight='bold')
axes[0].set_xlabel('Class', fontsize=12)
axes[0].set_ylabel('Number of Messages', fontsize=12)
axes[0].set_title('Sample Count per Class', fontsize=13)
axes[0].set_ylim(0, max(class_counts.values) * 1.25)
axes[0].spines[['top','right']].set_visible(False)

# Pie chart
axes[1].pie(
    class_counts.values,
    labels=[f'{l.upper()}\n({v} msgs)' for l, v in zip(class_counts.index, class_counts.values)],
    colors=COLORS,
    autopct='%1.1f%%',
    startangle=90,
    wedgeprops={'edgecolor': 'white', 'linewidth': 2},
    textprops={'fontsize': 11}
)
axes[1].set_title('Percentage Share per Class', fontsize=13)

plt.tight_layout()
plt.savefig('visuals/chart2_class_distribution.png', dpi=300, bbox_inches='tight')
plt.show()
print('Saved: visuals/chart2_class_distribution.png')

"""## Chart 3 — Confusion Matrix Heatmap (per model)"""

def plot_confusion(ax_raw, ax_norm, cm, title):
    cm_norm = cm.astype('float') / cm.sum(axis=1, keepdims=True) * 100

    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
                linewidths=0.5, ax=ax_raw, cbar=False)
    ax_raw.set_title(f'{title}\n(Raw Counts)', fontsize=11, fontweight='bold')
    ax_raw.set_xlabel('Predicted Label', fontsize=10)
    ax_raw.set_ylabel('Actual Label', fontsize=10)

    sns.heatmap(cm_norm, annot=True, fmt='.1f', cmap='Reds',
                xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
                linewidths=0.5, ax=ax_norm, cbar=False)
    ax_norm.set_title(f'{title}\n(Row-Normalised %)', fontsize=11, fontweight='bold')
    ax_norm.set_xlabel('Predicted Label', fontsize=10)
    ax_norm.set_ylabel('Actual Label', fontsize=10)

models_cm = [
    (cm_nb,   'Naive Bayes (TF-IDF)'),
    (cm_lr,   'Logistic Regression (TF-IDF)'),
    (cm_w2v,  'Logistic Regression (Word2Vec)'),
]

fig, axes = plt.subplots(3, 2, figsize=(12, 16))
fig.suptitle('Chart 3 — Confusion Matrices (All Models)', fontsize=15, fontweight='bold')

for row, (cm, title) in enumerate(models_cm):
    plot_confusion(axes[row][0], axes[row][1], cm, title)

plt.tight_layout()
plt.savefig('visuals/chart3_confusion_matrices.png', dpi=300, bbox_inches='tight')
plt.show()
print('Saved: visuals/chart3_confusion_matrices.png')

"""## Chart 4 — Model Comparison Grouped Bar Chart"""

metric_cols = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
models      = metrics['Model'].tolist()
x           = np.arange(len(metric_cols))
n_models    = len(models)
bar_width   = 0.22
bar_colors  = ['#3498db', '#e74c3c', '#2ecc71', '#9b59b6']

fig, ax = plt.subplots(figsize=(14, 7))

for i, (model, color) in enumerate(zip(models, bar_colors)):
    values = metrics[metrics['Model'] == model][metric_cols].values[0]
    offset = (i - n_models/2 + 0.5) * bar_width
    bars = ax.bar(x + offset, values, bar_width,
                  label=model, color=color, edgecolor='white', linewidth=0.8)
    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + 0.005,
                f'{val:.2f}',
                ha='center', va='bottom', fontsize=8.5, fontweight='bold')

ax.set_xticks(x)
ax.set_xticklabels(metric_cols, fontsize=12)
ax.set_ylabel('Score', fontsize=12)
ax.set_title('Chart 4 — Model Comparison Across All Metrics', fontsize=14, fontweight='bold')
ax.set_ylim(0, 1.12)
ax.legend(fontsize=10, loc='lower right')
ax.spines[['top','right']].set_visible(False)
ax.yaxis.grid(True, linestyle='--', alpha=0.5)
ax.set_axisbelow(True)

plt.tight_layout()
plt.savefig('visuals/chart4_model_comparison.png', dpi=300, bbox_inches='tight')
plt.show()
print('Saved: visuals/chart4_model_comparison.png')

"""## Chart 5 — Top 20 Most Frequent Words per Class"""

spam_words = Counter(' '.join(df[df['label']=='spam']['text_clean'].dropna()).split())
ham_words  = Counter(' '.join(df[df['label']=='ham']['text_clean'].dropna()).split())

top_spam = pd.DataFrame(spam_words.most_common(20), columns=['word','count'])
top_ham  = pd.DataFrame(ham_words.most_common(20),  columns=['word','count'])

fig, axes = plt.subplots(1, 2, figsize=(16, 8))
fig.suptitle('Chart 5 — Top 20 Most Frequent Words per Class\n(after full preprocessing)',
             fontsize=14, fontweight='bold')

# SPAM
axes[0].barh(top_spam['word'][::-1], top_spam['count'][::-1],
             color='#e74c3c', edgecolor='white')
axes[0].set_title('SPAM — Top 20 Words', fontsize=13, color='#c0392b', fontweight='bold')
axes[0].set_xlabel('Frequency', fontsize=11)
for i, (word, count) in enumerate(zip(top_spam['word'][::-1], top_spam['count'][::-1])):
    axes[0].text(count + 1, i, str(count), va='center', fontsize=9)
axes[0].spines[['top','right']].set_visible(False)

# HAM
axes[1].barh(top_ham['word'][::-1], top_ham['count'][::-1],
             color='#3498db', edgecolor='white')
axes[1].set_title('HAM — Top 20 Words', fontsize=13, color='#2980b9', fontweight='bold')
axes[1].set_xlabel('Frequency', fontsize=11)
for i, (word, count) in enumerate(zip(top_ham['word'][::-1], top_ham['count'][::-1])):
    axes[1].text(count + 1, i, str(count), va='center', fontsize=9)
axes[1].spines[['top','right']].set_visible(False)

plt.tight_layout()
plt.savefig('visuals/chart5_top20_words.png', dpi=300, bbox_inches='tight')
plt.show()
print('Saved: visuals/chart5_top20_words.png')

"""## Chart 6 — Text Length Distribution"""

spam_lengths = df[df['label']=='spam']['word_count']
ham_lengths  = df[df['label']=='ham']['word_count']

spam_mean = spam_lengths.mean()
ham_mean  = ham_lengths.mean()

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Chart 6 — Text Length Distribution by Class', fontsize=14, fontweight='bold')

# Overlapping histograms
axes[0].hist(ham_lengths,  bins=40, alpha=0.6, color='#3498db', label='Ham',  edgecolor='white')
axes[0].hist(spam_lengths, bins=40, alpha=0.6, color='#e74c3c', label='Spam', edgecolor='white')
axes[0].axvline(ham_mean,  color='#2980b9', linestyle='--', linewidth=2,
                label=f'Ham mean ({ham_mean:.1f} words)')
axes[0].axvline(spam_mean, color='#c0392b', linestyle='--', linewidth=2,
                label=f'Spam mean ({spam_mean:.1f} words)')
axes[0].set_xlabel('Word Count', fontsize=12)
axes[0].set_ylabel('Number of Messages', fontsize=12)
axes[0].set_title('Overlapping Histogram', fontsize=13)
axes[0].legend(fontsize=10)
axes[0].spines[['top','right']].set_visible(False)

# Side-by-side boxplots
box_data = [ham_lengths.values, spam_lengths.values]
bp = axes[1].boxplot(box_data, labels=['Ham', 'Spam'], patch_artist=True,
                     medianprops={'color':'white','linewidth':2})
for patch, color in zip(bp['boxes'], ['#3498db', '#e74c3c']):
    patch.set_facecolor(color)
    patch.set_alpha(0.7)
axes[1].axhline(ham_mean,  color='#2980b9', linestyle='--', linewidth=1.5,
                label=f'Ham mean ({ham_mean:.1f})')
axes[1].axhline(spam_mean, color='#c0392b', linestyle='--', linewidth=1.5,
                label=f'Spam mean ({spam_mean:.1f})')
axes[1].set_xlabel('Class', fontsize=12)
axes[1].set_ylabel('Word Count', fontsize=12)
axes[1].set_title('Side-by-Side Boxplot', fontsize=13)
axes[1].legend(fontsize=10)
axes[1].spines[['top','right']].set_visible(False)

plt.tight_layout()
plt.savefig('visuals/chart6_text_length.png', dpi=300, bbox_inches='tight')
plt.show()
print('Saved: visuals/chart6_text_length.png')

"""## Export All Charts"""

import zipfile

charts = [
    'visuals/chart1_wordcloud.png',
    'visuals/chart2_class_distribution.png',
    'visuals/chart3_confusion_matrices.png',
    'visuals/chart4_model_comparison.png',
    'visuals/chart5_top20_words.png',
    'visuals/chart6_text_length.png',
]

with zipfile.ZipFile('member4_charts.zip', 'w') as z:
    for chart in charts:
        if os.path.exists(chart):
            z.write(chart)
            print(f'  Added: {chart}')
        else:
            print(f'  MISSING: {chart} — run that cell first')

print('\nDone! Download member4_charts.zip from the Files panel.')